### ISSUE TITLE
don't include specific UI framework in template

### ISSUE THREAD

**Issue by evdama** [mightyjol/sapper-firebase-template#1]
https://github.com/mightyjol/sapper-firebase-template/blob/2d0d5550834e84882fd85d16965a0a71b2d6a1c3/package.json#L30

thanks for the template, will start using it...
one thing I notice, since I use [UIkit with the CDN links](https://getuikit.com/docs/installation#download) is that you've hardcoded Bulma. It's a presumption regarding a UI lib, something I think shouldn't be in an app template?

**Comment by mightyjol** [comment]
good point, bulma is my preferred framework and i kinda forgot about it

**Comment by mightyjol** [comment]
2d0d5550834e84882fd85d16965a0a71b2d6a1c3
