### ISSUE TITLE
why put firebase-admin as project dependency

### ISSUE THREAD

**Issue by evdama** [mightyjol/sapper-firebase-template#4]
https://github.com/mightyjol/sapper-firebase-template/blob/91f068ef1b529bb8d44bdc124d2ba5ee6b6efa7e/package.json#L20

Hi, why did you put firebase-admin as project dependency and not a development dependency like the other firebase libs? Not an issue, just asking... :)

**Comment by mightyjol** [comment]
firebase-admin cannot be present on the client side (because it bypasses a lot of security measures on your firebase app)
But if you want to use it on your sapper server, you need it in dependencies
still it probably needs to be moved to the dependencies inside the functions folder

**Comment by evdama** [comment]
right, understood. thanks.
